// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"eventdispatch/app/auth/rpc/internal/logic"
	"eventdispatch/app/auth/rpc/internal/svc"
	"eventdispatch/app/auth/rpc/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}
